// GitHub v0.1.0
// This theme is generated by a converter script.
// Original Textmate Theme: GitHub by Martin Kühl. A theme based on the GitHub code stylesheet.
// The conversion is still incomplete. Any suggestions or any problems,
// please contact me at yanyu [at] cyblogic [dot] com.
// More at http://github.com/yanyu/github.tmtheme

GHEditorFG = '#000000';
GHEditorBG = '#F8F8FF';
GHEditorCursor = '#000';
GHEditorSelection = '#FFFFAA';
GHEditorMatch = '#FF6';
GHEditorBracketMatch = GHEditorMatch;
GHEditorCurrentLine = '#FFFEEB';
GHComment = '#999988';
GHBlockComment = '#999988';
GHHtmlComment = '#999988';
GHStringLiteral = '#DD1144';
GHRegularExpression = '#009926';
GHInterpolation = '#DD1144';
GHRubyInterpolation = '#DD1144';
GHDocument = '#DD1144';
GHNumber = '#009999';
GHRubyNumber = '#009999';
GHInteger = '#009999';
GHFloat = '#009999';
GHKeyword = {color: '#000000', bold: true};
GHJavascriptKeyword = {color: '#000000', bold: true};
GHObjcKeyword = {color: '#000000', bold: true};
GHPreprocessing = '#000000';
GHRubyClassName = {color: '#445588', bold: true};
GHConstantName = '#008080';
GHBuiltinConstant = {color: '#000000', bold: true};
GHCharacterConstant = '#DD1144';
GHEscape = '#666666';
GHBlock = '#000000';
GHSymbol = '#990073';
GHVariable = '#0086B3';
GHRubyVariable = '#0086B3';
GHRubyInstanceVariable = '#0086B3';
GHRubyClassVariable = '#0086B3';
GHRubyGlobalVariable = '#0086B3';
GHPunctuator = '#666666';
GHOperator = {color: '#000000', bold: true};
GHArrayBracket = '#000000';
GHBackslashSequence = '#000000';
GHTag = '#000000';
GHTagName = '#000080';
GHTagOpen = '#000000';
GHTagClose = '#000000';
GHTagOther = '#000000';
GHTagAttribute = '#008080';
GHTagValue = '#000000';
GHErbTag = '#000000';

charcoal.themes["GitHub"] =
{
	displayName: "GitHub",

	layers: {
		"ruby": {
			"Comment": GHComment,
			"BlockComment": GHBlockComment,
			"Block": GHBlock,
			"Interpolation": GHInterpolation,
			"String": GHStringLiteral,
			"Document": GHDocument,
			"Keyword": GHKeyword,
			"DeclarationKeyword": GHKeyword,
			"Builtin": GHBuiltinConstant,
			"LocalName": GHRubyVariable,
			"MemberName": GHRubyInstanceVariable,
			"ClassMemberName": GHRubyClassVariable,
			"ClassName": GHRubyClassName,
			"ConstantName": GHConstantName,
			"GlobalName": GHRubyGlobalVariable,
			"Symbol": GHSymbol,
			"OpeningBracket": GHArrayBracket,
			"ClosingBracket": GHArrayBracket,
			"Float": GHFloat,
			"Integer": GHInteger,
			"Operator": GHOperator,
			"EscapeSequence": GHEscape
		},
		"python": {
			"Comment": GHComment,
			"String": GHStringLiteral,
			"Keyword": GHKeyword,
			"Identifier": GHKeyword,
			"Operator": GHOperator,
			"Float": GHFloat,
			"Integer": GHInteger
		},
		"javascript": {
			"Comment": GHComment,
			"Keyword": GHJavascriptKeyword,
			"ReservedWord": GHJavascriptKeyword,
			"FutureReservedWord": GHJavascriptKeyword,
			"Identifier": GHOperator,
			"DecimalLiteral": GHNumber,
			"HexIntegerLiteral": GHNumber,
			"StringLiteral": GHStringLiteral,
			"EscapeSequence": GHEscape,
			"BackslashSequence": GHBackslashSequence,
			"RegularExpressionLiteral": GHRegularExpression,
			"Punctuator" : GHPunctuator,
			"DivPunctuator" : GHPunctuator
		},
		"xml": {
			"Comment": GHHtmlComment,
			"TagName": GHTagName,
			"TagOpen": GHTagOpen,
			"TagClose": GHTagClose,
			"AttributeName": GHTagAttribute,
			"AttributeValue": GHTagValue,
			"ScriptTagName": GHTagOther
		},
		"erb": {
			"ErbComment": GHComment,
			"ErbStart": GHErbTag,
			"ErbEnd": GHErbTag
		},
		"cxx": {
			"BlockComment": GHBlockComment,
			"LineComment": GHComment,
			"PreprocessingComment": GHComment,
			"Preprocessing": GHPreprocessing,
			"EscapedChar": GHEscape,
			"String": GHStringLiteral,
			"ObjcEscapedChar": GHEscape,
			"ObjcString": GHStringLiteral,
			"Keyword": GHKeyword,
			"TypeKeyword": GHKeyword,
			"QtKeyword": GHKeyword,
			"ObjcKeyword": GHObjcKeyword,
			"Integer": GHInteger,
			"Float": GHFloat,
			"Char": GHCharacterConstant,
			"Punctuator" : GHPunctuator
		},
		"bash": {
			"Comment": GHComment,
			"SingleQuoted": GHStringLiteral,
			"DoubleQuoted": GHStringLiteral,
			"Document": GHDocument,
			"EscapedChar": GHEscape,
			"Expansion": GHInterpolation,
			"Operator": GHOperator,
			"Builtin": GHBuiltinConstant,
			"Reserved": GHKeyword,
			"Integer": GHInteger
		}
	},
	
	editor: {
		foreground: GHEditorFG,
		background: GHEditorBG,
		cursor: GHEditorCursor,
		lineNumbers: "#808080",
		lineNumbersBright: "#000",
		lineNumbersBackground: "#F2F2F2",
		lineNumbersBackgroundBright: "#E5E5E5",
		selection: GHEditorSelection,
		match: GHEditorMatch,
		bracketMatch: GHEditorBracketMatch,
		currentLine: GHEditorCurrentLine
	}
};
