// Ryan Light v0.1.0
// This theme is generated by a converter script.
// Original Textmate Theme: "Ryan Light" copyright by Ryan Bates (see RyanLight.copying).
// The conversion is still incomplete. Any suggestions or any problems,
// please contact me at yanyu [at] cyblogic [dot] com.
// More at http://github.com/yanyu/textmate-themes

RLEditorFG = '#000000';
RLEditorBG = '#FFFFFF';
RLEditorCursor = '#000';
RLEditorSelection = '#C3DCFF';
RLEditorMatch = '#FF6';
RLEditorBracketMatch = RLEditorMatch;
RLEditorCurrentLine = '#EFEFEF';
RLComment = '#808080';
RLBlockComment = '#808080';
RLHtmlComment = '#808080';
RLStringLiteral = '#0E8D90';
RLRegularExpression = '#0E8D90';
RLInterpolation = '#26B31A';
RLRubyInterpolation = '#26B31A';
RLDocument = '#0E8D90';
RLNumber = '#0900D3';
RLRubyNumber = '#0900D3';
RLInteger = '#0900D3';
RLFloat = '#0900D3';
RLKeyword = '#006A08';
RLJavascriptKeyword = '#006A08';
RLObjcKeyword = '#820095';
RLPreprocessing = '#000000';
RLRubyClassName = '#000000';
RLConstantName = '#A62B29';
RLBuiltinConstant = '#0000CD';
RLCharacterConstant = '#A62B29';
RLEscape = '#000000';
RLBlock = '#000000';
RLSymbol = '#A62B29';
RLVariable = '#7E3700';
RLRubyVariable = '#7E3700';
RLRubyInstanceVariable = '#7E3700';
RLRubyClassVariable = '#7E3700';
RLRubyGlobalVariable = '#7E3700';
RLPunctuator = '#000000';
RLOperator = '#006A08';
RLArrayBracket = '#000000';
RLBackslashSequence = '#000000';
RLTagName = '#2D439B';
RLTagOpen = '#2D439B';
RLTagClose = '#2D439B';
RLTagOther = '#2D439B';
RLTagAttribute = '#2D439B';
RLTagValue = '#2D439B';
RLErbTag = '#000000';

charcoal.themes["Ryan Light"] =
{
	displayName: "Ryan Light",

	layers: {
		"ruby": {
			"Comment": RLComment,
			"BlockComment": RLBlockComment,
			"Block": RLBlock,
			"Interpolation": RLInterpolation,
			"String": RLStringLiteral,
			"Document": RLDocument,
			"Keyword": RLKeyword,
			"DeclarationKeyword": RLKeyword,
			"Builtin": RLBuiltinConstant,
			"LocalName": RLRubyVariable,
			"MemberName": RLRubyInstanceVariable,
			"ClassMemberName": RLRubyClassVariable,
			"ClassName": RLRubyClassName,
			"ConstantName": RLConstantName,
			"GlobalName": RLRubyGlobalVariable,
			"Symbol": RLSymbol,
			"OpeningBracket": RLArrayBracket,
			"ClosingBracket": RLArrayBracket,
			"Float": RLFloat,
			"Integer": RLInteger,
			"Operator": RLOperator,
			"EscapeSequence": RLEscape
		},
		"python": {
			"Comment": RLComment,
			"String": RLStringLiteral,
			"Keyword": RLKeyword,
			"Identifier": RLKeyword,
			"Operator": RLOperator,
			"Float": RLFloat,
			"Integer": RLInteger
		},
		"javascript": {
			"Comment": RLComment,
			"Keyword": RLJavascriptKeyword,
			"ReservedWord": RLJavascriptKeyword,
			"FutureReservedWord": RLJavascriptKeyword,
			"Identifier": RLOperator,
			"DecimalLiteral": RLNumber,
			"HexIntegerLiteral": RLNumber,
			"StringLiteral": RLStringLiteral,
			"EscapeSequence": RLEscape,
			"BackslashSequence": RLBackslashSequence,
			"RegularExpressionLiteral": RLRegularExpression,
			"Punctuator" : RLPunctuator,
			"DivPunctuator" : RLPunctuator
		},
		"xml": {
			"Comment": RLHtmlComment,
			"TagName": RLTagName,
			"TagOpen": RLTagOpen,
			"TagClose": RLTagClose,
			"AttributeName": RLTagAttribute,
			"AttributeValue": RLTagValue,
			"ScriptTagName": RLTagOther
		},
		"erb": {
			"ErbComment": RLComment,
			"ErbStart": RLErbTag,
			"ErbEnd": RLErbTag
		},
		"cxx": {
			"BlockComment": RLBlockComment,
			"LineComment": RLComment,
			"PreprocessingComment": RLComment,
			"Preprocessing": RLPreprocessing,
			"EscapedChar": RLEscape,
			"String": RLStringLiteral,
			"ObjcEscapedChar": RLEscape,
			"ObjcString": RLStringLiteral,
			"Keyword": RLKeyword,
			"TypeKeyword": RLKeyword,
			"QtKeyword": RLKeyword,
			"ObjcKeyword": RLObjcKeyword,
			"Integer": RLInteger,
			"Float": RLFloat,
			"Char": RLCharacterConstant,
			"Punctuator" : RLPunctuator
		},
		"bash": {
			"Comment": RLComment,
			"SingleQuoted": RLStringLiteral,
			"DoubleQuoted": RLStringLiteral,
			"Document": RLDocument,
			"EscapedChar": RLEscape,
			"Expansion": RLInterpolation,
			"Operator": RLOperator,
			"Builtin": RLBuiltinConstant,
			"Reserved": RLKeyword,
			"Integer": RLInteger
		}
	},
	
	editor: {
		foreground: RLEditorFG,
		background: RLEditorBG,
		cursor: RLEditorCursor,
		lineNumbers: "#808080",
		lineNumbersBright: "#000",
		lineNumbersBackground: "#F2F2F2",
		lineNumbersBackgroundBright: "#E5E5E5",
		selection: RLEditorSelection,
		match: RLEditorMatch,
		bracketMatch: RLEditorBracketMatch,
		currentLine: RLEditorCurrentLine
	}
};
